# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
        ),
    ]
